### ISSUE TITLE
发送成功，gmail接收到了，但是voice中没有信息，显示出错

### ISSUE THREAD

**Issue by midpoint** [KarlLee830/GoogleVoiceAutoSMS#1]
![gv1](https://github.com/user-attachments/assets/5b6980fc-0987-46f0-a140-8c5022b627e9)

**Comment by karllee830** [comment]
你的邮件地址不对
下面是正确地址的示例
19783330234.12013900209.VhFKRs9JaG@txt.voice.google.com
